alias vi='vim'
alias lls='ls -hlF'
alias lla='ls -AhlF'
alias la='ls -AF'
alias rgrep='rgrep --color=always -n'
alias lt='tree -Ch --dirsfirst'
alias lta='tree -aCh --dirsfirst'
alias pt='tree -Ch --dirsfirst --charset=ASCII'
alias pta='tree -aCh --dirsfirst --charset=ASCII'
alias diff='diff -y --suppress-common-lines'
alias ps='ps -eo pid,user,cmd'
alias less='less -R'
alias vpnc='sudo vpnc'
alias vpncd='sudo vpnc-disconnect'
alias ta='tmux attach'

alias apti='sudo aptitude install'
alias aptu='sudo aptitude update'
alias aptuu='sudo aptitude update && sudo aptitude safe-upgrade'
alias apts='sudo aptitude search'
alias aptr='sudo aptitude remove'
alias aptc='sudo aptitude clean'

alias yumi='sudo yum install'
alias yumu='sudo yum update'
alias yums='sudo yum search'
alias yuml='sudo yum list'

alias ppjson='python -mjson.tool'
alias ppxml='python -c "import sys, xml.dom.minidom; print xml.dom.minidom.parseString(sys.stdin.read()).toprettyxml()"'

alias il='inova-login'
alias sn='supernova'
